install compatibility with new PROTEUS install.sh script
These three changes were necessary to install AGNI on my machine (macOS,
Julia 1.11.9) using the new PROTEUS install.sh script.
The build.jl addition fixes the following error I get when it gets run:

ERROR: LoadError: ArgumentError: Package Glob not found in current path.
- Run `import Pkg; Pkg.add("Glob")` to install the Glob package.
Stacktrace:
  [1] macro expansion
    @ ./loading.jl:2296 [inlined]
  [2] macro expansion
    @ ./lock.jl:273 [inlined]
  [3] __require(into::Module, mod::Symbol)
    @ Base ./loading.jl:2271
  [4] #invoke_in_world#3
    @ ./essentials.jl:1089 [inlined]
  [5] invoke_in_world
    @ ./essentials.jl:1086 [inlined]
  [6] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:2260
  [7] include(fname::String)
    @ Main ./sysimg.jl:38
  [8] top-level scope
    @ [PROTEUS_DIR]/socrates/julia/src/generate_wrappers.jl:13
  [9] include(fname::String)
    @ Main ./sysimg.jl:38
 [10] top-level scope
    @ [PROTEUS_DIR]/AGNI/deps/build.jl:16
in expression starting at [PROTEUS_DIR]/socrates/julia/src/clean_wrappers.jl:3
in expression starting at [PROTEUS_DIR]/socrates/julia/src/generate_wrappers.jl:13
in expression starting at [PROTEUS_DIR]/AGNI/deps/build.jl:16

The get_agni.sh change removes the git pull that is incompatible with
the new pinning mechanism in PROTEUS install.sh, because it checks out a
specific commit which git cannot automatically link to a branch, because
it may be in multiple branches, and if there is no branch there can be
no git pull, so that command currently fails the install script.

The runtests.jl change just makes the interpretation of the 0 argument
the same as in PROTEUS, because PROTEUS assumes it means "no tests",
whereas in runtests.jl it was set to run the fast suite. This would be
fine on most platforms, but it fails on macOS, because the blake test
fails there. A better fix would probably be to skip the blake test on
macOS, because I see it is not expected to work outside of Linux anyway,
but this is a quick workaround.